### ISSUE TITLE
Update app

### ISSUE THREAD

**Issue by tanujdhiman** [Mandal-21/Flight-Price-Prediction#4]
Hello, 
Your code is good enough but it is just predict for some places. We can improve this by adding more places.
Thanks.

**Comment by Mandal-21** [comment]
Yes, we can do that @tanujdhiman

**Comment by vaibhavshah1234** [comment]
i am try to deploy through Heroku but my model is unable to build look here ....how to solve this plzz tell
![Screenshot (4)](https://user-images.githubusercontent.com/69906280/118986974-704c8880-b99d-11eb-998d-9c53191c1b38.png)

**Comment by vaibhavshah1234** [comment]
and all the requirements are satisfied to soo where is the problem
![Screenshot (5)](https://user-images.githubusercontent.com/69906280/118987488-ecdf6700-b99d-11eb-9734-02134770cd57.png)

**Comment by vaibhavshah1234** [comment]
you can just have a look on my Repositorie,
https://github.com/vaibhavshah1234/flight_price_prediction.git

**Comment by tanujdhiman** [comment]
@vaibhavshah1234 Why are giving a lot of libraries in requirements.txt ? Only relevant libraries should have to give. And also I think you should not give any python requirement in file. Because other libraries are not compatible with python version 2. Try to do this. 

Thanks

**Comment by tanujdhiman** [comment]
UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\tanuj\Downloads\flight_price_prediction-main\flight\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator RandomForestRegressor from version 0.22.1 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


These are the users warning it is giving. Please make first model good.

**Comment by vaibhavshah1234** [comment]
THANK YOU  soo much for your changes in the code it made my task easy and now i haved deployed it .
@tanujdhiman

**Comment by tanujdhiman** [comment]
@vaibhavshah1234 Can you provide the link of the Deployed app?

And also Please update your readme file in repository. It left a great impact on any viewer.
Sample :- https://github.com/tanujdhiman/Bank_Customer_Deployed_Model
Thanks.

**Comment by vaibhavshah1234** [comment]
@tanujdhiman here i attach my deployed app link .
https://vs-fly.herokuapp.com/

yes, i will add readme file for viewer .
Thanks

**Comment by vaibhavshah1234** [comment]
@tanujdhiman can you please give your social handle soo iff any issue in future i will contact you directly . like now i will work on Bank coustomer project soo thatswhy i am looking for your contact if you are comfortable.

**Comment by tanujdhiman** [comment]
@vaibhavshah1234 https://www.linkedin.com/in/tanuj-dhiman-a5647a16b/ Linkedln Profile.

I've a suggestion for you. Actually model is quite good but prediction is behind so that when I first ran it feels me like it is not running. So It's your choice. It's just a suggestion.

BTW it is great.
Thanks.

**Comment by tanujdhiman** [comment]
Okay I am closing this issue. 

Thank you. @Mandal-21 @vaibhavshah1234
